In [1]:
import numpy as np
from scipy import ndimage
import os

import nibabel as nib 

In [2]:
def recursive_glob_files(top_folder_path, file_format):
    gathered_file_pathes = []

    for (root, directories, files) in os.walk(top_folder_path):
        for file in files:
            if file_format in file:
                detect_file_path = os.path.join(root, file)
                gathered_file_pathes.append(detect_file_path)

    return gathered_file_pathes


In [3]:
task2_train_data_path = r'C:\Users\parkm\Desktop\github\analysis_nifti_for_deeplearning\data\task2\Training'

task2_train_data_path_list =  recursive_glob_files(task2_train_data_path, '.nii.gz')

task2_train_mask_data_path_list = [x for x in task2_train_data_path_list if x.endswith('mask.nii.gz')]

In [7]:
import SimpleITK as sitk

In [8]:
task2_train_data_path_list[0]

'C:\\Users\\parkm\\Desktop\\github\\analysis_nifti_for_deeplearning\\data\\task2\\Training\\R001\\sub-r001s001\\ses-1\\anat\\sub-r001s001_ses-1_space-MNI152NLin2009aSym_label-L_desc-T1lesion_mask.nii.gz'

In [22]:
raw_nii = nib.load(task2_train_data_path_list[0])
raw_nii_array = raw_nii.get_fdata()
raw_affine = raw_nii.affine

In [66]:
raw_nii_array.shape

(197, 233, 189)

In [44]:
non_zeros = np.nonzero(raw_nii_array)

In [65]:
non_zeros

(array([ 70,  70,  70, ..., 166, 166, 166], dtype=int64),
 array([133, 134, 134, ..., 125, 126, 126], dtype=int64),
 array([62, 60, 61, ..., 96, 95, 96], dtype=int64))

In [53]:
x_min = non_zeros[0].min()
x_max = non_zeros[0].max()

y_min = non_zeros[1].min()
y_max = non_zeros[1].max()

z_min = non_zeros[2].min()
z_max = non_zeros[2].max()

In [57]:
xmin_list, xmax_list, ymin_list, ymax_list, zmin_list, zmax_list = [],[],[],[],[],[]


for i in range(50):
    raw_nii = nib.load(task2_train_data_path_list[i])
    raw_nii_array = raw_nii.get_fdata()

    x_min = non_zeros[0].min()
    x_max = non_zeros[0].max()

    y_min = non_zeros[1].min()
    y_max = non_zeros[1].max()

    z_min = non_zeros[2].min()
    z_max = non_zeros[2].max()
    
    xmin_list.append(x_min)
    xmax_list.append(x_max)
    
    ymin_list.append(y_min)
    ymax_list.append(y_max)
    
    zmin_list.append(z_min)
    zmax_list.append(z_max)

In [69]:
xmin_list


[70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70]

In [70]:
xmax_list

[166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166,
 166]

In [68]:
ymin_list

[81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81,
 81]

In [67]:
ymax_list

[187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 187]

In [72]:
zmin_list

[48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48]

In [71]:
zmax_list

[139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139,
 139]