In [1]:
import numpy as np
from scipy import ndimage
import os

import nibabel as nib 

In [2]:
def recursive_glob_files(top_folder_path, file_format):
    gathered_file_pathes = []

    for (root, directories, files) in os.walk(top_folder_path):
        for file in files:
            if file_format in file:
                detect_file_path = os.path.join(root, file)
                gathered_file_pathes.append(detect_file_path)

    return gathered_file_pathes


In [3]:
task2_train_data_path = r'C:\Users\parkm\Desktop\github\analysis_nifti_for_deeplearning\data\task2\Training'

task2_train_data_path_list =  recursive_glob_files(task2_train_data_path, '.nii.gz')

task2_train_mask_data_path_list = [x for x in task2_train_data_path_list if x.endswith('mask.nii.gz')]

In [4]:
import SimpleITK as sitk

In [5]:
task2_train_data_path_list[0]

'C:\\Users\\parkm\\Desktop\\github\\analysis_nifti_for_deeplearning\\data\\task2\\Training\\R001\\sub-r001s001\\ses-1\\anat\\sub-r001s001_ses-1_space-MNI152NLin2009aSym_label-L_desc-T1lesion_mask.nii.gz'

### 1. non-zero로 3d array의 non-zero 좌표 가져와서 확인하기
- background cleansing, skull stripping이 잘되어서 배경이 모두 0로 잘 정리되었을 경우에 사용가능

In [6]:
raw_nii = nib.load(task2_train_data_path_list[0])
raw_nii_array = raw_nii.get_fdata()
raw_affine = raw_nii.affine

In [7]:
raw_nii_array.shape

(197, 233, 189)

In [8]:
non_zeros = np.nonzero(raw_nii_array)

In [9]:
non_zeros

(array([ 70,  70,  70, ..., 166, 166, 166], dtype=int64),
 array([133, 134, 134, ..., 125, 126, 126], dtype=int64),
 array([62, 60, 61, ..., 96, 95, 96], dtype=int64))

In [10]:
x_min = non_zeros[0].min()
x_max = non_zeros[0].max()

y_min = non_zeros[1].min()
y_max = non_zeros[1].max()

z_min = non_zeros[2].min()
z_max = non_zeros[2].max()

In [11]:
xmin_list, xmax_list, ymin_list, ymax_list, zmin_list, zmax_list = [],[],[],[],[],[]


for i in range(50):
    raw_nii = nib.load(task2_train_data_path_list[i])
    raw_nii_array = raw_nii.get_fdata()
    non_zeros = np.nonzero(raw_nii_array)

    x_min = non_zeros[0].min()
    x_max = non_zeros[0].max()

    y_min = non_zeros[1].min()
    y_max = non_zeros[1].max()

    z_min = non_zeros[2].min()
    z_max = non_zeros[2].max()
    
    xmin_list.append(x_min)
    xmax_list.append(x_max)
    
    ymin_list.append(y_min)
    ymax_list.append(y_max)
    
    zmin_list.append(z_min)
    zmax_list.append(z_max)

In [12]:
xmin_list


[70,
 0,
 69,
 0,
 73,
 0,
 60,
 0,
 53,
 0,
 60,
 0,
 110,
 0,
 61,
 0,
 116,
 0,
 118,
 0,
 121,
 0,
 61,
 0,
 55,
 0,
 60,
 0,
 62,
 0,
 61,
 0,
 60,
 0,
 65,
 0,
 67,
 0,
 102,
 0,
 61,
 0,
 99,
 0,
 89,
 0,
 114,
 0,
 115,
 0]

In [13]:
xmax_list

[166,
 196,
 171,
 196,
 123,
 196,
 156,
 196,
 83,
 196,
 131,
 196,
 131,
 196,
 140,
 196,
 170,
 196,
 173,
 196,
 159,
 196,
 82,
 196,
 129,
 196,
 89,
 196,
 113,
 196,
 124,
 196,
 117,
 196,
 73,
 196,
 170,
 196,
 165,
 196,
 139,
 196,
 105,
 196,
 90,
 196,
 123,
 196,
 131,
 196]

In [14]:
ymin_list

[81,
 0,
 55,
 0,
 115,
 0,
 54,
 0,
 69,
 0,
 107,
 0,
 107,
 0,
 98,
 0,
 43,
 0,
 79,
 0,
 99,
 0,
 78,
 0,
 40,
 0,
 70,
 0,
 106,
 0,
 99,
 0,
 87,
 0,
 128,
 0,
 79,
 0,
 89,
 0,
 94,
 0,
 103,
 0,
 116,
 0,
 112,
 0,
 116,
 0]

In [15]:
ymax_list

[187,
 232,
 183,
 232,
 142,
 232,
 146,
 232,
 174,
 232,
 176,
 232,
 166,
 232,
 143,
 232,
 173,
 232,
 170,
 232,
 163,
 232,
 145,
 232,
 136,
 232,
 169,
 232,
 143,
 232,
 148,
 232,
 158,
 232,
 137,
 232,
 172,
 232,
 172,
 232,
 135,
 232,
 107,
 232,
 119,
 232,
 137,
 232,
 134,
 232]

In [16]:
zmin_list

[48,
 0,
 17,
 0,
 78,
 0,
 9,
 0,
 58,
 0,
 45,
 0,
 55,
 0,
 25,
 0,
 76,
 0,
 29,
 0,
 63,
 0,
 69,
 0,
 58,
 0,
 69,
 0,
 68,
 0,
 60,
 0,
 28,
 0,
 58,
 0,
 49,
 0,
 15,
 0,
 41,
 0,
 38,
 0,
 49,
 0,
 80,
 0,
 58,
 0]

In [17]:
zmax_list

[139,
 188,
 120,
 188,
 110,
 188,
 154,
 188,
 122,
 188,
 102,
 188,
 98,
 188,
 108,
 188,
 141,
 188,
 133,
 188,
 112,
 188,
 124,
 188,
 145,
 188,
 120,
 188,
 114,
 188,
 97,
 188,
 109,
 188,
 68,
 188,
 138,
 188,
 114,
 188,
 102,
 188,
 43,
 188,
 51,
 188,
 96,
 188,
 98,
 188]

### 2. 중심 복셀 기준으로 단면을 자르고, 뇌에 접하는 육방면체 구하기
- 1의 방법으로는 back-ground cleansing이 제대로 안되어있으면 최대최소값이 다르게 나옴